Repository goorm-engineers4/MSA_people_of_delivery, pull requests merged in 2025-08, with the labels that each got.

#14 🔨 [Refactor] store-service 추가 파일
  store-service/build.gradle
  store-service/gradle/wrapper/gradle-wrapper.jar
  store-service/gradle/wrapper/gradle-wrapper.properties
  store-service/gradlew
  store-service/gradlew.bat
  store-service/src/docker-compose.yml
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/StoreRepository.java
Labels: ⚙ Setting, 🔨 Refactor

#17 🔨 [REFACTOR] store-serivce MSA, 모듈별 db 분리
  cart-service/docker-compose.yml
  cart-service/src/main/java/com/example/cloudfour/cartservice/CartServiceApplication.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/commondto/StoreResponseDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/order/controller/OrderController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/order/converter/OrderItemConverter.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/order/repository/OrderItemRepository.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/order/service/query/OrderQueryServiceImpl.java
  module-common/docker-compose.yml
  settings.gradle
  store-service/build.gradle
  store-service/docker-compose.yml
  store-service/src/main/java/com/example/cloudfour/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/example/cloudfour/storeservice/config/GatewayPrincipal.java
  store-service/src/main/java/com/example/cloudfour/storeservice/config/RestTemplateConfig.java
  store-service/src/main/java/com/example/cloudfour/storeservice/config/security/GatewayAuthHeaderFilter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/config/security/SecurityConfig.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/commondto/OrderItemResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/MenuCommonRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/MenuController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/converter/MenuOptionConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/MenuOptionResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/MenuRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/entity/MenuCategory.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/entity/MenuOption.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/exception/MenuCategoryErrorCode.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/exception/MenuCategoryException.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/exception/MenuErrorCode.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/exception/MenuException.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/exception/MenuOptionErrorCode.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/exception/MenuOptionException.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuOptionRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/command/MenuCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/query/MenuQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/entity/Region.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/exception/RegionErrorCode.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/exception/RegionException.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/service/RegionService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreCommonResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/converter/StoreConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/dto/StoreResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/entity/Store.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/exception/StoreCategoryErrorCode.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/exception/StoreCategoryException.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/exception/StoreErrorCode.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/exception/StoreException.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/StoreRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryService.java
  store-service/src/main/resources/application.yml
Labels: 🔨 Refactor

#13 ✨ [FEAT] user-service 모듈 생성
  apigateway/build.gradle
  apigateway/src/main/java/com/example/cloudfour/apigateway/config/RestTemplateConfig.java
  apigateway/src/main/java/com/example/cloudfour/apigateway/config/SecurityConfig.java
  apigateway/src/main/java/com/example/cloudfour/apigateway/controller/AuthProxyController.java
  apigateway/src/main/java/com/example/cloudfour/apigateway/jwt/JwtUtil.java
  apigateway/src/main/resources/application.yml
  user-service/build.gradle
  user-service/docker-compose.yml
  user-service/gradle/wrapper/gradle-wrapper.jar
  user-service/gradle/wrapper/gradle-wrapper.properties
  user-service/gradlew
  user-service/gradlew.bat
  user-service/src/main/java/com/example/cloudfour/userservice/UserServiceApplication.java
  user-service/src/main/java/com/example/cloudfour/userservice/config/EmailConfig.java
  user-service/src/main/java/com/example/cloudfour/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/controller/AuthCommonResponseDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/controller/AuthController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/converter/AuthConverter.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/dto/AuthRequestDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/dto/AuthResponseDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/dto/TokenDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/entity/VerificationCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/enums/VerificationPurpose.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/exception/AuthErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/exception/AuthException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/repository/VerificationCodeRepository.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/service/AuthService.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/service/EmailService.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/service/EmailServiceImpl.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/entity/Region.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/exception/RegionErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/exception/RegionException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/repository/RegionRepository.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/service/RegionService.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/util/RegionParser.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/controller/UserController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/converter/UserConverter.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/dto/UserRequestDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/dto/UserResponseDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/entity/User.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/entity/UserAddress.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/enums/LoginType.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/enums/Role.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserAddressErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserAddressException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/repository/UserAddressRepository.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/repository/UserRepository.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/service/UserAddressService.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/service/UserService.java
  user-service/src/main/java/com/example/cloudfour/userservice/security/GatewayAuthHeaderFilter.java
  user-service/src/main/java/com/example/cloudfour/userservice/security/GatewayPrincipal.java
  user-service/src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#21 🐛 [FIX] user-service 빌드 오류 해결
  apigateway/src/main/java/com/example/cloudfour/apigateway/jwt/JwtProperties.java
  settings.gradle
  user-service/docker-compose.yml
  user-service/src/main/java/com/example/cloudfour/userservice/UserServiceApplication.java
  user-service/src/main/java/com/example/cloudfour/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/controller/AuthController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/exception/AuthErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/exception/AuthException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/entity/Region.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/exception/RegionErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/exception/RegionException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/controller/UserController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/entity/User.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserAddressErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserAddressException.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserErrorCode.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/exception/UserException.java
Labels: 🐞 BugFix

#26 🔨 [REFACTOR] user service 내 JWT 발급 추가
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/controller/AuthController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/converter/AuthConverter.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/dto/AuthRequestDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/dto/AuthResponseDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/dto/RefreshDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/entity/RefreshToken.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/repository/RefreshTokenRepository.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/service/AuthService.java
  user-service/src/main/java/com/example/cloudfour/userservice/security/jwt/JwtProperties.java
  user-service/src/main/java/com/example/cloudfour/userservice/security/jwt/JwtUtil.java
  user-service/src/main/resources/application.yml
Labels: 🔨 Refactor

#15 ✨ [FEAT] ai-service 모듈 생성
  ai-service/Dockerfile
  ai-service/build.gradle
  ai-service/gradle/wrapper/gradle-wrapper.jar
  ai-service/gradle/wrapper/gradle-wrapper.properties
  ai-service/gradlew
  ai-service/gradlew.bat
  ai-service/src/main/java/com/example/cloudfour/aiservice/AiServiceApplication.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/builder/ProductPromptBuilder.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/builder/RestaurantPromptBuilder.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/builder/WeatherMenuPromptBuilder.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/client/GeminiClient.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/client/UserServiceClient.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/client/WeatherClient.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/commondto/StoreResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/commondto/UserAddressResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/commondto/UserResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/config/WebClientConfig.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/constants/CityTranslator.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/constants/WeatherConstants.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/controller/ProductDescriptionController.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/controller/RestaurantDescriptionController.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/controller/WeatherMenuController.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/converter/ProductDescriptionConverter.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/converter/RestaurantDescriptionConverter.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/converter/WeatherMenuConverter.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/GeminiRequestDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/GeminiResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/ProductDescriptionRequestDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/ProductDescriptionResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/RestaurantDescriptionRequestDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/RestaurantDescriptionResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/WeatherMenuRequestDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/dto/WeatherMenuResponseDTO.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/entity/AiLog.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/exception/AiLogErrorCode.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/exception/AiLogException.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/global/entity/BaseEntity.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/parser/ProductDescriptionResponseParser.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/parser/RestaurantDescriptionResponseParser.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/parser/WeatherMenuResponseParser.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/repository/AiLogRepository.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/service/command/ProductDescriptionCommandServiceImpl.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/service/command/RestaurantDescriptionCommandServiceImpl.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/service/command/WeatherMenuCommandServiceImpl.java
  ai-service/src/main/resources/application.yml
Labels: ✨ Feature

#31 :hammer: [REFACTOR] ai msa 전환
  ai-service/Dockerfile
  ai-service/build.gradle
  ai-service/src/main/java/com/example/cloudfour/aiservice/entity/AiLog.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/exception/AiLogErrorCode.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/exception/AiLogException.java
  ai-service/src/main/java/com/example/cloudfour/aiservice/global/entity/BaseEntity.java
  ai-service/src/main/resources/application.yml
  settings.gradle
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/repository/RegionRepository.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/region/service/RegionService.java
Labels: 🔨 Refactor

#33 🔨 [REFACTOR] 실행 오류 수정
  apigateway/build.gradle
  apigateway/src/main/java/com/example/cloudfour/apigateway/filter/AuthFilter.java
  apigateway/src/main/java/com/example/cloudfour/apigateway/filter/AuthPermissionFilter.java
  apigateway/src/main/java/com/example/cloudfour/apigateway/jwt/JwtUtil.java
  apigateway/src/main/resources/application.yml
  user-service/src/main/java/com/example/cloudfour/userservice/domain/auth/controller/AuthController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/controller/UserController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/dto/UserRequestDTO.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/entity/UserAddress.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/service/UserAddressService.java
  user-service/src/main/java/com/example/cloudfour/userservice/security/jwt/JwtUtil.java
Labels: 🔨 Refactor

#37 ✨ [FEAT] 사용자 주소 추가
  cart-service/src/main/java/com/example/cloudfour/cartservice/cart/entity/Cart.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/order/entity/Order.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/entity/Review.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/entity/UserAddress.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/enums/AddressStatus.java
Labels: ✨ Feature, 🔨 Refactor

#41 ✨ [FEAT] store,menu에 권한 추가
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/MenuController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/command/MenuCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/query/MenuQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/service/command/ReviewCommandServiceImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/service/query/ReviewQueryServiceImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/command/StoreCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryService.java
Labels: ✨ Feature

#39 ✨ [FEAT] store-service에 querydsl 추가
  module-common/build.gradle
  store-service/build.gradle
  store-service/src/main/java/com/example/cloudfour/storeservice/config/QueryDslConfig.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuCategoryRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuOptionRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/querydsl/MenuCategoryQueryDslRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/querydsl/MenuCategoryQueryDslRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/querydsl/MenuOptionQueryDslRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/querydsl/MenuOptionQueryDslRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/querydsl/MenuQueryDslRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/querydsl/MenuQueryDslRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/repository/RegionQueryDslRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/repository/RegionQueryDslRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/region/repository/RegionRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/StoreCategoryRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/StoreRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/querydsl/StoreCategoryQueryDslRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/querydsl/StoreCategoryQueryDslRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/querydsl/StoreQueryDslRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/querydsl/StoreQueryDslRepositoryImpl.java
Labels: ✨ Feature

#67 ✨ [FEAT] MongoDB 동기화
  ai-service/src/main/java/com/example/cloudfour/aiservice/config/SwaggerConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/CartServiceApplication.java
  store-service/src/main/java/com/example/cloudfour/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/converter/DocumentConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/document/StoreDocument.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/command/MenuCommandRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/command/MenuCommandRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/command/ReviewCommandRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/command/ReviewCommandRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/command/ReviewCustomCommandRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/command/StoreCommandRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/collection/repository/query/StoreSearchRepositoryImpl.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/OrderItemResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/RegionResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/UserResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/common/enums/SyncStatus.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/converter/MenuConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/MenuResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/entity/Menu.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/entity/MenuCategory.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/entity/MenuOption.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuOptionRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/repository/MenuRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/command/MenuCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/controller/ReviewController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/dto/ReviewRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/dto/ReviewResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/entity/Review.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/repository/ReviewRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/service/command/ReviewCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/service/query/ReviewQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/converter/StoreConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/dto/StoreRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/dto/StoreResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/entity/Store.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/entity/StoreCategory.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/repository/StoreRepository.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/command/StoreCommandService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryService.java
  store-service/src/main/java/com/example/cloudfour/storeservice/scheduler/MongoCreatedSyncScheduler.java
  store-service/src/main/java/com/example/cloudfour/storeservice/scheduler/MongoDeletedSyncScheduler.java
  store-service/src/main/java/com/example/cloudfour/storeservice/scheduler/MongoUpdatedSyncScheduler.java
  store-service/src/main/java/com/example/cloudfour/storeservice/scheduler/StoreServiceScheduler.java
Labels: ✨ Feature

#70 🔨 [REFACTOR] cart-service 로직 수정
  cart-service/src/main/java/com/example/cloudfour/cartservice/aspect/PerformanceAspect.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/StoreClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/UserClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/CacheConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/RestTemplateConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/controller/CartController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/converter/CartConverter.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/dto/CartRequestDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/dto/CartResponseDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/entity/Cart.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/exception/CartErrorCode.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/repository/CartRepository.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/service/command/CartCommandService.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/service/query/CartQueryService.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/controller/CartItemCommonResponseDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/controller/CartItemController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/converter/CartItemConverter.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/dto/CartItemRequestDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/entity/CartItem.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/entity/CartItemOption.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/exception/CartItemErrorCode.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/repository/CartItemRepository.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/service/command/CartItemCommandService.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/service/query/CartItemQueryService.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/controller/OrderController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/converter/OrderConverter.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/converter/OrderItemConverter.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/dto/OrderItemResponseDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/dto/OrderRequestDTO.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/entity/Order.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/entity/OrderItem.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/entity/OrderItemOption.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/enums/OrderStatus.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/enums/OrderType.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/enums/ReceiptType.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/exception/OrderErrorCode.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/repository/OrderItemOptionRepository.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/repository/OrderRepository.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/service/command/OrderCommandService.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/service/query/OrderQueryService.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#77 ✨ [FEAT] 재고 internalController, DTO에 @Valid 추가
  ai-service/build.gradle
  apigateway/build.gradle
  auth-service/build.gradle
  cart-service/build.gradle
  module-common/build.gradle
  store-service/build.gradle
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/InternalStockController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/MenuCommonRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/MenuController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/StockResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/controller/ReviewCommonRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/controller/ReviewController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreCommonRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/dto/StoreRequestDTO.java
  user-service/build.gradle
Labels: ✨ Feature

#84 🔨 [REFACTOR] 재고 확인 internalController 수정
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/InternalStockController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/converter/StockConverter.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/StockResponseDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/query/StockQueryService.java
Labels: 🔨 Refactor

#83 :memo: [DOCS] 모니터링 메트릭 수집
  payment-service/build.gradle
Labels: 📃 Docs

#86 ✨ [FEAT] 권한 검증 추가
  auth-service/src/main/java/com/example/cloudfour/authservice/domain/auth/controller/AuthController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/controller/CartController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cartitem/controller/CartItemController.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/controller/OrderController.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/controller/PaymentController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/controller/MenuController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/review/controller/ReviewController.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/store/controller/StoreController.java
  user-service/src/main/java/com/example/cloudfour/userservice/domain/user/controller/UserController.java
Labels: ✨ Feature

#88 🔨 [REFACTOR] 재고 수량 수정
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/dto/MenuRequestDTO.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/entity/Stock.java
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/command/MenuCommandService.java
Labels: 🔨 Refactor

#89 ✨ [FEAT] 주문, 결제 Kafka 추가
  cart-service/build.gradle
  cart-service/src/main/java/com/example/cloudfour/cartservice/client/StoreClient.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/KafkaConsumerConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/config/KafkaProducerConfig.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/cart/entity/Cart.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/exception/StockErrorCode.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/exception/StockException.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/domain/order/service/command/OrderCommandService.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/event/OrderCreatedEvent.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/event/PaymentApprovedEvent.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/event/PaymentFailedEvent.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/listener/PaymentEventListener.java
  cart-service/src/main/java/com/example/cloudfour/cartservice/service/OrderEventPublishService.java
  cart-service/src/main/resources/application.yml
  payment-service/build.gradle
  payment-service/src/main/java/com/example/cloudfour/paymentservice/config/KafkaConfig.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/entity/Payment.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/event/OrderCreatedEvent.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/event/PaymentApprovedEvent.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/event/PaymentFailedEvent.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/service/EventPublishService.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/domain/payment/service/command/PaymentCommandServiceImpl.java
  payment-service/src/main/java/com/example/cloudfour/paymentservice/listener/OrderEventListener.java
  payment-service/src/main/resources/application.yml
  store-service/src/main/java/com/example/cloudfour/storeservice/domain/menu/service/query/StockQueryService.java
Labels: ✨ Feature, 🔨 Refactor

#90 🧪 [TEST] Store-Service 테스트 코드 작성
  store-service/build.gradle
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/command/MenuCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/command/StockCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/query/MenuQueryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/menu/service/query/StockQueryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/region/service/RegionServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/review/service/command/ReviewCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/review/service/query/ReviewQueryServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/store/service/command/StoreCommandServiceTest.java
  store-service/src/test/java/com/example/cloudfour/storeservice/domain/store/service/query/StoreQueryServiceTest.java
  store-service/src/test/resources/application-test.yml
Labels: Test
